version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword

  nginx:
    image: nginx:1.15.0-alpine
    ports:
      - "8080:80"
    depends_on:
      - app
